// Generated by ts-to-zod
import { z } from "zod";

const spotlightPostSchemaSchema = z.object({
    id: z.string(),
    thumbnail: z.string(),
    cover: z.string(),
    content: z.string(),
    createdById: z.string(),
    createdByName: z.string(),
    symbol: z.union([z.string(), z.undefined()]).optional().nullable(),
    title: z.union([z.string(), z.undefined()]).optional().nullable(),
    category: z.union([z.string(), z.undefined()]).optional(),
    icon: z.union([z.string(), z.undefined()]).optional(),
    createdAt: z.union([z.date(), z.undefined()]).optional(),
    updatedAt: z.union([z.date(), z.undefined()]).optional()
});
